l_french:
 impart_values.0001.t:0 "Inculquer une leçon de vie"
 impart_values.0001.desc:0 "#italic Ah, la jeunesse. Cette fougue, cette vigueur. Tout un monde à découvrir. Alors même que votre propre personnalité reste votre plus grand mystère.#!\n\nTandis que je réfléchis à l'inconstance de la jeunesse, [recipient.Custom('FR_le_Char_Pi')][recipient.GetTitledFirstName], M[ROOT.Char.Custom2('FR_RelationToMeShort_OnA', recipient)] [recipient.Custom('InsultAdjective')], entre en scène avec son manque d'attention habituel.\n\nIl est temps d'y remédier : #bold Je vais donner à cet enfant une leçon sur ce qui est important dans la vie.#!"
 already_imparted_lesson_desc:0 "Vous avez déjà essayé d'enseigner vos valeurs à [CHARACTER.GetShortUINameNoTooltip]."
 impart_values.0001.diligent:0 "Enseigner les bienfaits d'un travail acharné."
 impart_values.0001.lazy:0 "Enseigner les bienfaits de laisser les autres s'occuper des problèmes."
 impart_values.0001.cynical:0 "Enseigner les bienfaits de toujours douter de tout."
 impart_values.0001.zealous:0 "Enseigner les bienfaits d'une dévotion totale et absolue."
 impart_values.0001.brave:0 "Enseigner les bienfaits de la bravoure et de l'audace."
 impart_values.0001.craven:0 "Enseigner les bienfaits de ne jamais s'exposer au danger."
 impart_values.0001.calm:0 "Enseigner les bienfaits de ne jamais perdre son sang-froid."
 impart_values.0001.wrathful:0 "Enseigner les bienfaits à laisser éclater sa fureur."
 impart_values.0001.chaste:0 "Enseigner les bienfaits à réprouver ses pulsions charnelles."
 impart_values.0001.lustful:0 "Enseigner les bienfaits de ne pas réfréner ses besoins naturels."
 impart_values.0001.content:0 "Enseigner les bienfaits à se satisfaire du nécessaire."
 impart_values.0001.ambitious:0 "Enseigner les bienfaits à toujours vouloir plus."
 impart_values.0001.fickle:0 "Enseigner les bienfaits d'être versatile et imprévisible."
 impart_values.0001.stubborn:0 "Enseigner les bienfaits de l'obstination envers et contre tout."
 impart_values.0001.forgiving:0 "Enseigner les bienfaits du pardon et de la clémence."
 impart_values.0001.vengeful:0 "Enseigner les bienfaits de la rancœur et de la vengeance."
 impart_values.0001.generous:0 "Enseigner les bienfaits du dévouement désintéressé à son prochain."
 impart_values.0001.greedy:0 "Enseigner les bienfaits à privilégier l'or plus que tout au monde."
 impart_values.0001.gregarious:0 "Enseigner les bienfaits de la compagnie d'autrui."
 impart_values.0001.shy:0 "Enseigner les bienfaits de la solitude."
 impart_values.0001.honest:0 "Enseigner les bienfaits de privilégier la vérité et la sincérité."
 impart_values.0001.deceitful:0 "Enseigner les bienfaits à jouer un rôle en toute circonstance."
 impart_values.0001.humble:0 "Enseigner les bienfaits de la modestie."
 impart_values.0001.arrogant:0 "Enseigner les bienfaits de ne jamais effacer ni son orgueil ni sa fierté."
 impart_values.0001.just:0 "Enseigner les bienfaits du respect des lois des dieux et des hommes."
 impart_values.0001.arbitrary:0 "Enseigner les bienfaits de suivre sa volonté au détriment du reste."
 impart_values.0001.patient:0 "Enseigner les bienfaits de ne pas précipiter les choses."
 impart_values.0001.impatient:0 "Enseigner les bienfaits à obtenir le plus vite possible des résultats."
 impart_values.0001.temperate:0 "Enseigner les bienfaits de la retenue et de la modération."
 impart_values.0001.gluttonous:0 "Enseigner les bienfaits de ne jamais se priver de quoi que ce soit."
 impart_values.0001.trusting:0 "Enseigner les bienfaits d'avoir une totale confiance en les autres."
 impart_values.0001.paranoid:0 "Enseigner les bienfaits de rester sur le qui-vive à tout instant."
 impart_values.0001.compassionate:0 "Enseigner les bienfaits de l'empathie et de la bienveillance."
 impart_values.0001.callous:0 "Enseigner les bienfaits de ne jamais se préoccuper des autres."
 impart_values.0001.sadistic:0 "Enseigner les bienfaits que peut apporter la souffrance d'autrui."
 impart_values.0001.rude:0 "Enseigner les bienfaits de s'exprimer sans détour ni ménagement."
 impart_values.0001.honorable:0 "Enseigner les bienfaits d'être quelqu'un de respectable."
 impart_values.0001.ruthless:0 "Enseigner les bienfaits de ne s'imposer aucune limite."
 impart_values.0001.authoritative:0 "Enseigner les bienfaits de savoir s'imposer."
 impart_values.0001.backout:0 "Finalement nous reporterons cela à une prochaine fois."
 impart_values_lesson_ignored_title:0 "Leçon ignorée"
 impart_values_lesson_ignored_desc:0 "[recipient.GetShortUINameNoTooltip] n'a montré aucun intérêt pour vos leçons."
 impart_values_lesson_success_title:0 "Réussite de la leçon"
 impart_values_lesson_success_desc:0 "[recipient.GetShortUINameNoTooltip] a pris vos leçons à coeur et a acquis le trait [recipient.Custom('TraitLearned')]."
 impart_values_lesson_failure_title:0 "Échec de la leçon"
 impart_values_lesson_failure_desc:0 "[recipient.GetShortUINameNoTooltip] s'est opposé à vos leçons et a acquis le trait [recipient.Custom('TraitLearned')]."
 impart_values.0001.inquisitive:0 "Enseigner les bienfaits de la quête de connaissance."